# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Author.create(name:"J.R.R. Tolkein",age:81)
Author.create(name:"Tracy Hickman",age:66)
Author.create(name:"Lloyd Alexander",age:83)
Author.create(name:"C.S. Lewis",age:64)
Author.create(name:"Brandon Sanderson",age:46)
Author.create(name:"Neil Gaiman",age:61)
Author.create(name:"Cassandra Clare",age:48)
Author.create(name:"Terry Pratchett",age:66)
Author.create(name:"Sarah J. Maas",age:35)
Author.create(name:"Richelle Mead",age:45)
Author.create(name:"Anne Rice","age":80)


Book.create(name:'The Hobbit', genre:'Fantasy', author_id:1)
Book.create(name:'The Lord of the Rings', genre:'Fantasy', author_id:1)
Book.create(name:'The Silmarillion', genre:'Fantasy', author_id:1)
Book.create(name:'Dragons of Autumn Twilight', genre:'Fantasy', author_id:2)
Book.create(name:'Dragons of Winter Night', genre:'Fantasy', author_id:2)
Book.create(name:'Dragons of Spring Dawning', genre:'Fantasy', author_id:2)
Book.create(name:'Test of the Twins', genre:'Fantasy', author_id:2)
Book.create(name:'Time of the Twins', genre:'Fantasy', author_id:2)
Book.create(name:'War of the Twins', genre:'Fantasy', author_id:2)
Book.create(name:'The Book of Three', genre:'Fantasy', author_id:3)
Book.create(name:'The Black Cauldron', genre:'Fantasy', author_id:3)
Book.create(name:'Taran Wanderer', genre:'Fantasy', author_id:3)
Book.create(name:'The High King', genre:'Fantasy', author_id:3)
Book.create(name:'The Castle of Llyr', genre:'Fantasy', author_id:3)
Book.create(name:'The Lion, the Witch and the Wardrobe', genre:'Fantasy', author_id:4)
Book.create(name:'The Voyage of the Dawn Treader', genre:'Fantasy', author_id:4)
Book.create(name:'Prince Caspian', genre:'Fantasy', author_id:4)
Book.create(name:'The Last Battle', genre:'Fantasy', author_id:4)
Book.create(name:'The Silver Chair', genre:'Fantasy', author_id:4)
Book.create(name:'The Way of Kings', genre:'Fantasy', author_id:5)
Book.create(name:'Words of Radiance', genre:'Fantasy', author_id:5)
Book.create(name:'Oathbringer', genre:'Fantasy', author_id:5)
Book.create(name:'Rythm of War', genre:'Fantasy', author_id:5)
Book.create(name:'American Gods', genre:'Fantasy', author_id:6)
Book.create(name:'Stardust', genre:'Fantasy', author_id:6)
Book.create(name:'Neverwhere', genre:'Fantasy', author_id:6)
Book.create(name:'The Graveyard Book', genre:'Fantasy', author_id:6)
Book.create(name:'City of Bones', genre:'Fantasy', author_id:7)
Book.create(name:'City of Ashes', genre:'Fantasy', author_id:7)
Book.create(name:'City of Glass', genre:'Fantasy', author_id:7)
Book.create(name:'City of Fallen Angels', genre:'Fantasy', author_id:7)
Book.create(name:'City of Lost Souls', genre:'Fantasy', author_id:7)
Book.create(name:'City of Heavenly Fire', genre:'Fantasy', author_id:7)
Book.create(name:'The Color of Magic', genre:'Fantasy', author_id:8)
Book.create(name:'Mort', genre:'Fantasy', author_id:8)
Book.create(name:'Hogfather', genre:'Fantasy', author_id:8)
Book.create(name:'Reaper Man', genre:'Fantasy', author_id:8)
Book.create(name:'A Court of Thorns and Roses', genre:'Fantasy Romance', author_id:9)
Book.create(name:'A Court of Mist and Fury', genre:'Fantasy Romance', author_id:9)
Book.create(name:'A Court of Wings and Ruin', genre:'Fantasy Romance', author_id:9)
Book.create(name:'A Court of Frost and Starlight', genre:'Fantasy Romance', author_id:9)
Book.create(name:'A Court of Silver Flames', genre:'Fantasy Romance', author_id:9)
Book.create(name:'Vampire Academy', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Frostbite', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Shadow Kiss', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Blood Promise', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Spirit Bound', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Last Sacrifice', genre:'Paranormal Romance', author_id:10)
Book.create(name:'Interview with the Vampire', genre:'Horror', author_id:11)
Book.create(name:'The Vampire Lestat', genre:'Horror', author_id:11)
Book.create(name:'The Queen of the Damned', genre:'Horror', author_id:11)
Book.create(name:'The Tale of the Body Thief', genre:'Horror', author_id:11)
Book.create(name:'Memnoch the Devil', genre:'Horror', author_id:11)
Book.create(name:'The Vampire Armand', genre:'Horror', author_id:11)
Book.create(name:'Merrick', genre:'Horror', author_id:11)
Book.create(name:'Blood and Gold', genre:'Horror', author_id:11)
Book.create(name:'Blackwood Farm', genre:'Horror', author_id:11)
Book.create(name:'Blood Canticle', genre:'Horror', author_id:11)
Book.create(name:'Prince Lestat', genre:'Horror', author_id:11)
Book.create(name:'Prince Lestat and the Ralms of Atlantis', genre:'Horror', author_id:11)
Book.create(name:'Blood Communion: A Tale of Prince Lestat', genre:'Horror', author_id:11)